### ISSUE TITLE
poi.js fails to start

### ISSUE THREAD

**Issue by iwei20** [U5B/jsmacros#2]
Fabric Loader 0.14.8, Java 17-OpenJ9 Semeru AdoptOpenJDK

Modlist:
![image](https://user-images.githubusercontent.com/44007607/181119527-67d51744-69b8-4732-962f-48e8b7626c58.png)
![image](https://user-images.githubusercontent.com/44007607/181119577-7a1b4bce-28d9-43d5-af98-277f5defb74c.png)

```
[17:56:17] [Render thread/INFO]: [CHAT] java.lang.ArrayIndexOutOfBoundsException\n at String.getBytes (String.java 5214:?)\n at StringConcatHelper.prepend (StringConcatHelper.java 356:?)\n at StringConcatHelper.prepend (StringConcatHelper.java 373:?)\n at LambdaForm$DMH/0x000000007ceeda00.invokeStatic (LambdaForm$DMH)\n at LambdaForm$MH/0x000000007d311f50.invoke (LambdaForm$MH)\n at LambdaForm$MH/0x000000007c949e50.invoke (LambdaForm$MH)\n at LambdaForm$MH/0x000000007cd0d730.linkToTargetMethod (LambdaForm$MH)\n at CommonJSResolution.joinPaths (CommonJSResolution.java 364:?)\n at CommonJSResolution.resolve (CommonJSResolution.java 179:?)\n at CommonJSRequireBuiltin.requireImpl (CommonJSRequireBuiltin.java 159:?)\n at CommonJSRequireBuiltin.require (CommonJSRequireBuiltin.java 144:?)\n at CommonJSRequireBuiltinNodeGen.execute (CommonJSRequireBuiltinNodeGen.java 47:?)\n at FunctionRootNode.executeInRealm (FunctionRootNode.java 149:?)\n at JavaScriptRealmBoundaryRootNode.execute (JavaScriptRealmBoundaryRootNode.java 92:?)\n at :program (poi.js 31:27)
java.lang.ArrayIndexOutOfBoundsException
	at java.base/java.lang.String.getBytes(String.java:5214)
	at java.base/java.lang.StringConcatHelper.prepend(StringConcatHelper.java:356)
	at java.base/java.lang.StringConcatHelper.prepend(StringConcatHelper.java:373)
	at java.base/java.lang.invoke.LambdaForm$DMH/0x000000007ceeda00.invokeStatic(LambdaForm$DMH)
	at java.base/java.lang.invoke.LambdaForm$MH/0x000000007d311f50.invoke(LambdaForm$MH)
	at java.base/java.lang.invoke.LambdaForm$MH/0x000000007c949e50.invoke(LambdaForm$MH)
	at java.base/java.lang.invoke.LambdaForm$MH/0x000000007cd0d730.linkToTargetMethod(LambdaForm$MH)
	at com.oracle.truffle.js.builtins.commonjs.CommonJSResolution.joinPaths(CommonJSResolution.java:364)
	at com.oracle.truffle.js.builtins.commonjs.CommonJSResolution.resolve(CommonJSResolution.java:179)
	at com.oracle.truffle.js.builtins.commonjs.CommonJSRequireBuiltin.requireImpl(CommonJSRequireBuiltin.java:159)
	at com.oracle.truffle.js.builtins.commonjs.CommonJSRequireBuiltin.require(CommonJSRequireBuiltin.java:144)
	at com.oracle.truffle.js.builtins.commonjs.CommonJSRequireBuiltinNodeGen.execute(CommonJSRequireBuiltinNodeGen.java:47)
	at com.oracle.truffle.js.nodes.function.FunctionRootNode.executeInRealm(FunctionRootNode.java:149)
	at com.oracle.truffle.js.runtime.JavaScriptRealmBoundaryRootNode.execute(JavaScriptRealmBoundaryRootNode.java:92)
	at com.oracle.truffle.api.impl.DefaultCallTarget.callDirectOrIndirect(DefaultCallTarget.java:85)
	at com.oracle.truffle.api.impl.DefaultDirectCallNode.call(DefaultDirectCallNode.java:59)
	at com.oracle.truffle.js.nodes.function.JSFunctionCallNode$UnboundJSFunctionCacheNode.executeCall(JSFunctionCallNode.java:1279)
	at com.oracle.truffle.js.nodes.function.JSFunctionCallNode.executeAndSpecialize(JSFunctionCallNode.java:305)
	at com.oracle.truffle.js.nodes.function.JSFunctionCallNode.executeCall(JSFunctionCallNode.java:250)
	at com.oracle.truffle.js.nodes.function.JSFunctionCallNode$CallNode.execute(JSFunctionCallNode.java:531)
	at com.oracle.truffle.js.nodes.function.JSFunctionCallNode$Call1Node.createArguments(JSFunctionCallNode.java:610)
	at com.oracle.truffle.js.nodes.function.JSFunctionCallNode$CallNode.execute(JSFunctionCallNode.java:531)
	at com.oracle.truffle.js.nodes.access.WritePropertyNode.executeAndSpecialize(WritePropertyNode.java:284)
	at com.oracle.truffle.js.nodes.access.WritePropertyNode.executeVoid(WritePropertyNode.java:256)
	at com.oracle.truffle.js.nodes.control.AbstractBlockNode.executeVoid(AbstractBlockNode.java:80)
	at com.oracle.truffle.js.nodes.control.AbstractBlockNode.executeVoid(AbstractBlockNode.java:55)
	at com.oracle.truffle.api.impl.DefaultBlockNode.executeGeneric(DefaultBlockNode.java:63)
	at com.oracle.truffle.js.nodes.control.AbstractBlockNode.execute(AbstractBlockNode.java:75)
	at com.oracle.truffle.js.nodes.binary.DualNode.execute(DualNode.java:125)
	at com.oracle.truffle.js.nodes.function.FunctionBodyNode.execute(FunctionBodyNode.java:73)
	at com.oracle.truffle.js.nodes.function.FunctionRootNode.executeInRealm(FunctionRootNode.java:149)
	at com.oracle.truffle.js.runtime.JavaScriptRealmBoundaryRootNode.execute(JavaScriptRealmBoundaryRootNode.java:92)
	at com.oracle.truffle.api.impl.DefaultCallTarget.callDirectOrIndirect(DefaultCallTarget.java:85)
	at com.oracle.truffle.api.impl.DefaultDirectCallNode.call(DefaultDirectCallNode.java:59)
	at com.oracle.truffle.js.lang.JavaScriptLanguage$ParsedProgramRoot.execute(JavaScriptLanguage.java:245)
	at com.oracle.truffle.api.impl.DefaultCallTarget.callDirectOrIndirect(DefaultCallTarget.java:85)
	at com.oracle.truffle.api.impl.DefaultCallTarget.call(DefaultCallTarget.java:102)
	at com.oracle.truffle.polyglot.PolyglotContextImpl.eval(PolyglotContextImpl.java:1326)
	at com.oracle.truffle.polyglot.PolyglotContextDispatch.eval(PolyglotContextDispatch.java:63)
	at org.graalvm.polyglot.Context.eval(Context.java:399)
	at xyz.wagyourtail.jsmacros.js.language.impl.GraalLanguageDefinition.exec(GraalLanguageDefinition.java:78)
	at xyz.wagyourtail.jsmacros.core.language.BaseLanguage.lambda$trigger$1(BaseLanguage.java:49)
	at xyz.wagyourtail.jsmacros.core.language.BaseLanguage$$Lambda$4378/0x000000000bae34a8.run(Unknown Source)
	at java.base/java.lang.Thread.run(Thread.java:884)
```

**Comment by U5B** [comment]
What version of Minecraft?
I have been only testing on 1.18.2

sorry for not responding earlier, I have been busy for this month

**Comment by iwei20** [comment]
1.18.2, yeah
